#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu-client
    password: $6$TzQJv0ZT$XKIOGtYAK8bgjKoH7Xx9OS6UR70WONnJ4TRx4b8Ih3/Eg0hP0vLQcOgW7aq/pmbnWDJWUp7HkQs65ELAzv.F0.
    username: test
  ssh:
    install-server: no
  storage:
    layout:
      name: direct
  keyboard:
    layout: de
  locale: de_DE
  packages:
    - ubuntu-desktop
  user-data:
    disable_root: false
  late-commands:
    - curtin in-target --target=/target -- sh -c 'echo "test ALL=(ALL) NOPASSWD:ALL" > /target/etc/sudoers.d/test'
    - curtin in-target --target=/target -- apt-get update
    - curtin in-target --target=/target -- apt-get upgrade -y
