#cloud-config
autoinstall:
  version: 1
  user-data:
    users: [""]
    disable_root: false
  ssh:
    install-server: no
  storage:
    layout:
      name: lvm
      password: ubuntu
  keyboard:
    layout: de
  locale: de_DE
  packages:
    - ubuntu-desktop
  snaps:
    - name: code
      classic: true
    - name: postman
      classic: false
    - name: powershell
      classic: true
  late-commands:
    - wget -O /target/postinstall.sh https://raw.githubusercontent.com/ugurkocde/Intune/main/Linux/postinstall.sh
    - curtin in-target -- bash /target/postinstall.sh
    - rm /target/postinstall.sh
    - curtin in-target --target=/target -- reboot
