#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu-client
    password: "$6$rounds=4096$5pLQJvKz9Dzi6ZfX$Tsu1L9M/2F/WQs1I4R4."
    username: test
  ssh:
    install-server: no
  storage:
    layout:
      name: direct
  keyboard:
    layout: de
    variant: de
  locale: de_DE
  packages:
    - ubuntu-desktop
  user-data:
    disable_root: false
  late-commands:
    - curtin in-target --target=/target -- sh -c 'echo "test ALL=(ALL) NOPASSWD:ALL" > /target/etc/sudoers.d/test'
    - curtin in-target --target=/target -- apt-get update
    - curtin in-target --target=/target -- apt-get upgrade -y
