#cloud-config
autoinstall:
  version: 1
  user-data:
    users: [""]
    disable_root: false
  ssh:
    install-server: no
  storage:
    layout:
      name: direct
  keyboard:
    layout: de
  locale: de_DE
  packages:
    - ubuntu-desktop
  late-commands:
    - curtin in-target --target=/target -- sh -c 'echo "test ALL=(ALL) NOPASSWD:ALL" > /target/etc/sudoers.d/test'
    - curtin in-target --target=/target -- apt-get update
    - curtin in-target --target=/target -- apt-get upgrade -y
