#cloud-config
autoinstall:
  version: 1
  user-data:
    users: [""]
    disable_root: false
  ssh:
    install-server: no
  storage:
    layout:
      name: lvm
      password: ubuntu
  keyboard:
    layout: de
  locale: de_DE
  packages:
    - ubuntu-desktop
  snaps:
    - name: code
      classic: true
    - name: postman
      classic: false
    - name: powershell
      classic: true
  late-commands:
    - curtin in-target --target=/target -- wget -O /usr/share/backgrounds/my_background.jpg https://raw.githubusercontent.com/ugurkocde/Intune/main/Linux/media/Thermenresort_Loipersdorf.jpg
    - curtin in-target --target=/target -- /bin/bash -c 'gsettings set org.gnome.desktop.background picture-uri "file:///usr/share/backgrounds/my_background.jpg"'
    - curtin in-target --target=/target -- reboot
